### ISSUE TITLE
[bug] `o200k_base` doesn't work with the package.

### ISSUE THREAD

**Issue by MurphyLo** [yaroslavyaroslav/SublimeTokenCounter#1]
Hi, I've been using sublime text 4 to format my prompts and your project really helps a lot! However the new `o200k_base` encoder seems to have some problem with the package. Modifying `Preferences.sublime-settings` or `Package Control.sublime-settings` by adding `"model_name": "gpt-4o", "tokenizer_encoding": "o200k_base",` seems to crash the package (the count results don't show up in the editor). Am I miconfiguring the package to change the encoder or `o200k_base` is not supported yet? Thank you for your help.

**Comment by yaroslavyaroslav** [comment]
Can't reproduce this. Is there some errors appearing in ST console about this?

**Comment by MurphyLo** [comment]
I modified the `Preferences.sublime-settings` file by adding `"model_name": "gpt-4o",`. After restarting ST, I selected some text and used the `Tokens Count` command from the command palette, then no token count text appeared, and the console output the following error:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 1693, in run_
    return self.run(edit)
  File "/Users/12345/Library/Application Support/Sublime Text/Installed Packages/TokensCounter.sublime-package/tokens_counter.py", line 34, in run
  File "/Users/12345/Library/Application Support/Sublime Text/Installed Packages/TokensCounter.sublime-package/tokens_counter.py", line 88, in close_phantom
AttributeError: 'TokensCountCommand' object has no attribute 'phantom_set'
```
It’s worth mentioning that the plugin worked fine initially (with the default `cl100k_base` tokenizer).

**Comment by MurphyLo** [comment]
Further testing shows adding `"tokenizer_encoding": "o200k_base"` to the configuration allows the `Tokens Count` command to display token count information. But it seems the tokenizer being used is still cl100k_base, as the results differ from what I would expect with `o200k_base` (especially noticeable with non-English text).

The console output appears to be truncated and shows:
```
/Users/12345/Library/Application Support/Sublime Text/Lib/python38/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
```

**Comment by yaroslavyaroslav** [comment]
Oh, that's bad. Seems like underneath dependency (requests) was added to Package Control in some buggy way. And most likely plugin fails to download some additional resource to handle non utf-8 chars. 

I'll raise this issue in the PC support channel, but can't promise anything here

**Comment by yaroslavyaroslav** [comment]
> I modified the Preferences.sublime-settings file by adding "model_name": "gpt-4o",.

Also I missed that bit, you shall not to change `Preferences.sublime-settings` directly, you should modify only `User.sublime-settings` for general sublime set up and the separate plugin settings files for each plugin. Please see the picture attached (it's right view where you should put your setup, no sublime restart required afterwards).
<img width="828" alt="Screenshot 2024-11-15 at 11 46 01" src="https://github.com/user-attachments/assets/d35de4a1-5df0-4936-9ed6-756b0376bb69">

**Comment by MurphyLo** [comment]
Thank you for your help! I'll try modifying the settings as you suggested.😀
